services:
  - type: web
    name: xeroxyt-nt
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node api/index.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
    autoDeploy: true
